Add retry mechanizm
allegro/envoy-control pull request #288
Opened 2022-02-04 08:19 UTC by malfoj89

2022-02-16 10:50 UTC, Ferdudas97 commented on envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadata.kt
> +        it.field("retryPolicy")?.let { retryPolicy ->
it could be reduced to `this?.field('retryPolcy)?.let{}`

2022-02-16 13:12 UTC, Ferdudas97 requested changes

2022-02-16 13:42 UTC, malfoj89 commented on envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadata.kt
> +                baseInterval = it.fieldsMap["baseInterval"]?.toDuration(),
and numberOfRetries

2022-02-22 08:13 UTC, Ferdudas97 commented on envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadata.kt
> +        retryHostPredicate = value.field("retryHostPredicate")?.let { retryHostPredicateField ->
unnecessary `?.let`

2022-02-22 08:13 UTC, Ferdudas97 commented on envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyEgressRoutesFactory.kt
> +                val retryBackOffBuilder = RetryPolicy.RetryBackOff.newBuilder()
it can be moved to `buildRetryBackOff`

2022-02-28 07:50 UTC, Ferdudas97 approved these changes

2022-02-28 10:15 UTC, KSmigielski requested changes

2022-02-28 10:15 UTC, KSmigielski commented on envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyEgressRoutesFactory.kt
> +            it.forEach { host ->
In my opinion it is hard to read. Consider something like that
```kotlin
val hostPredicates = it.map { RetryPolicy.RetryHostPredicate.newBuilder().setName(it.name).build() }
retryPolicyBuilder.addAllRetryHostPredicate(hostPredicates)
```

2022-02-28 10:15 UTC, KSmigielski commented on envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyEgressRoutesFactory.kt
> +            it.forEach { statusCode -> retryPolicyBuilder.addRetriableStatusCodes(statusCode) }
Why you not use `RetryPolicy.Builder#addAllRetriableStatusCodes` it make it simpler and then this method is useless

2022-02-28 10:15 UTC, KSmigielski commented on envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyEgressRoutesFactory.kt
> +            retryPolicy?.let { policy ->
I would consider to inline return in line 250

2022-02-28 18:41 UTC, KSmigielski approved these changes

2022-03-01 10:15 UTC, Ferdudas97 approved these changes

2022-03-01 10:24 UTC, merged