porpagate flags into lua filters
allegro/envoy-control pull request #327
Opened 2022-07-19 07:51 UTC by KSmigielski

2022-07-19 12:48 UTC, malfoj89 requested changes

2022-07-19 12:48 UTC, malfoj89 commented on envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/LuaFilterFactory.kt
> +                        .setStructValue(Struct.newBuilder()
maybe we should add test for this to ensure it works as desired

2022-07-19 20:09 UTC, malfoj89 requested changes

2022-07-19 20:09 UTC, malfoj89 commented on envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/LuaFilterFactoryTest.kt
> +        // when
please add line break as in above test

2022-07-19 20:09 UTC, malfoj89 commented on envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/LuaFilterFactoryTest.kt
> +        val expectedServiceName = "service-1"
missing // given

2022-07-19 20:09 UTC, malfoj89 commented on envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/LuaFilterFactoryTest.kt
> +    fun `should leave flags empty`() {
```suggestion
    fun `should setup flags empty if not specified`() {
```

2022-07-19 20:09 UTC, malfoj89 commented on envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/LuaFilterFactoryTest.kt
> +        assertThat(luaMetadata.getFieldsOrThrow("flags").structValue.allFields).isEmpty()
please add // then above

2022-07-19 20:09 UTC, malfoj89 commented on envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/LuaFilterFactoryTest.kt
> +        val metadata = factory.ingressScriptsMetadata(group)
i believe it belongs to given part as when part shall have only desired interaction

2022-07-19 20:09 UTC, malfoj89 commented on envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/LuaFilterFactoryTest.kt
> +        // then
add line break above // then

2022-07-19 20:09 UTC, malfoj89 commented on envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/LuaFilterFactoryTest.kt
> +        val metadata = factory.ingressScriptsMetadata(group, flags)
belong to given

2022-07-20 06:50 UTC, malfoj89 approved these changes

2022-07-21 10:44 UTC, gawarz approved these changes

2022-07-22 06:23 UTC, merged