Log authority in rbac
allegro/envoy-control pull request #330
Opened 2022-08-29 10:54 UTC by Ferdudas97

2022-08-30 06:16 UTC, KSmigielski submitted a review, later dismissed

2022-09-01 08:50 UTC, malfoj89 approved these changes

2022-09-01 13:36 UTC, malfoj89 submitted a review, later dismissed

2022-09-01 13:42 UTC, KSmigielski requested changes

2022-09-01 13:42 UTC, KSmigielski commented on CHANGELOG.md
> +## [0.19.16]
This is duplicated version

2022-09-02 07:29 UTC, malfoj89 approved these changes

2022-09-02 10:40 UTC, KSmigielski approved these changes

2022-09-02 10:40 UTC, merged