bump consul-recipes version
allegro/envoy-control pull request #352
Opened 2022-12-08 07:35 UTC by mzawirski

2022-12-08 15:38 UTC, malfoj89 approved these changes

2022-12-12 06:59 UTC, Ferdudas97 requested changes
it is ok but, we will merge it after https://github.com/allegro/envoy-control/pull/351

2022-12-14 06:37 UTC, Ferdudas97 approved these changes

2022-12-14 08:36 UTC, KSmigielski approved these changes

2022-12-14 09:15 UTC, merged